"""Initial migration

Revision ID: cb2e87f10443
Revises: 
Create Date: 2026-06-25 02:59:01.537861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2e87f10443'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.Column('monologue', sa.Text(), nullable=True),
    sa.Column('acting_notes', sa.Text(), nullable=True),
    sa.Column('similar_characters', sa.Text(), nullable=True),
    sa.Column('generation_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_id'), 'generations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generations_id'), table_name='generations')
    op.drop_table('generations')
    # ### end Alembic commands ###
